export const pEvent = [
    {
        title: 'Guardian Angel App',
        slug: 'guardian-angel-app',
        description: 'A mobile app that is used by people who have left rehab and need help in recovery process.',
        image: '',
        tech: ['React-Native', 'TypeScript', 'PostgreSQL', 'Stitch'],
        category: 'Frontend',
        github: 'https://github.com/Shantel300/GuardianAngelApp',
        demo: '',
        featured: true,
    },
    {
        title: 'Strain Engineering (Pvt) Ltd',
        slug: 'strain-engineering',
        description: 'Static Website for a construction company to show the projects and services they offer. Developed using plain HTML/CSS and JavaScript',
        image: '/images/strainengineering.png',
        tech: ['HTML', 'CSS', 'JavaScript'],
        category: 'Full Stack',
        github: 'https://github.com/elihu0430/Strain-Engineering-pvt',
        demo: 'https://strainengineeringpvt.vercel.app/',
        featured: true,
    },
    {
        title: 'MediClinic App',
        slug: 'mediclinic-app',
        description: 'A desktop app that was design in Java. It was developed to help in registering patients and tracking patient records with respect to their appointments',
        image: '/images/medic.png',
        tech: ['Java'],
        category: 'Full Stack',
        github: 'https://github.com/elihu0430/MedicClinic-App',
        demo: '',
    },
    {
        title: 'Bet Racing 365',
        slug: 'bet-racing-365',
        description: 'A desktop application design to record a horse racing event. Stores the records of the jockeys and horses that participated in the race',
        image: '/images/betracing.png',
        tech: ['Java'],
        category: 'Full Stack',
        github: 'https://github.com/elihu0430/BetRacing365',
        demo: '',
    },
]