import { Code2, Database, Monitor, Server, Settings, Zap } from '@/components/Icons'

export const sEvents = [
    {
        icon: Monitor,
        iconName: 'Monitor',
        title: 'Web Development',
        slug: 'web-development',
        description: 'Pixel-perfect, responsive websites built with modern HTML, CSS, and JavaScript. Fast, accessible, and optimized for every device.',
        items: ['Responsive layouts', 'Cross-browser compatibility', 'SEO best practices'],
        accent: 'bg-blue-50 dark:bg-blue-950/30 border-blue-200 dark:border-blue-800',
        iconBg: 'bg-blue-100 dark:bg-blue-900/60 text-blue-600 dark:text-blue-400',
    },
    {
        icon: Code2,
        iconName: 'Code2',
        title: 'Full-Stack Development',
        slug: 'full-stack-development',
        description: 'End-to-end application development from database schema to polished user interface, shipped to production.',
        items: ['Next.js & React apps', 'Node.js', 'Authentication & auth', '.Net & C#', 'Java'],
        accent: 'bg-teal-50 dark:bg-teal-950/30 border-teal-200 dark:border-teal-800',
        iconBg: 'bg-teal-100 dark:bg-teal-900/60 text-teal-600 dark:text-teal-400',
    },
    {
        icon: Zap,
        iconName: 'Zap',
        title: 'UI Implementation',
        slug: 'ui-implementation',
        description: 'Translating Figma designs into clean, maintainable React component libraries with design token systems.',
        items: ['Design system setup', 'Component libraries', 'Animation & interaction'],
        accent: 'bg-yellow-50 dark:bg-yellow-950/30 border-yellow-200 dark:border-yellow-800',
        iconBg: 'bg-yellow-100 dark:bg-yellow-900/60 text-yellow-600 dark:text-yellow-400',
    },
    {
        icon: Server,
        iconName: 'Server',
        title: 'API Development',
        slug: 'api-development',
        description: 'Scalable, well-documented APIs with authentication, rate limiting, and automated testing.',
        items: ['OpenAPI documentation', 'Rate limiting & security'],
        accent: 'bg-purple-50 dark:bg-purple-950/30 border-purple-200 dark:border-purple-800',
        iconBg: 'bg-purple-100 dark:bg-purple-900/60 text-purple-600 dark:text-purple-400',
    },
    {
        icon: Database,
        iconName: 'Database',
        title: 'Database Design',
        slug: 'database-design',
        description: 'Schema design, query optimisation, and migration strategies for SQL and NoSQL databases.',
        items: ['PostgreSQL & MongoDB', 'MySQL DB','Schema modeling', 'Performance optimization'],
        accent: 'bg-green-50 dark:bg-green-950/30 border-green-200 dark:border-green-800',
        iconBg: 'bg-green-100 dark:bg-green-900/60 text-green-600 dark:text-green-400',
    },
    {
        icon: Settings,
        iconName: 'Settings',
        title: 'Website Optimization',
        slug: 'website-optimization',
        description: 'Systematic performance audits and improvements: bundle analysis, lazy loading, caching, and Core Web Vitals.',
        items: ['Core Web Vitals', 'Bundle optimization', 'Caching strategies'],
        accent: 'bg-orange-50 dark:bg-orange-950/30 border-orange-200 dark:border-orange-800',
        iconBg: 'bg-orange-100 dark:bg-orange-900/60 text-orange-600 dark:text-orange-400',
    },
]